Refactor pipelines
pagopa/io-functions-template pull request #21
Opened 2021-03-24 18:14 UTC by balanza

#### List of Changes

* remove reference to legacy versions of azure templates
* remove local template for project setup 
* fix healthcheck endpoint

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-03-25 08:37 UTC, pasqualedevita requested changes

2021-03-25 08:37 UTC, pasqualedevita commented on .devops/code-review-pipelines.yml
> +      endpoint: 'pagopa'
```suggestion
      endpoint: 'io-azure-devops-github-ro'
```

2021-03-25 08:37 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
>        endpoint: 'pagopa'
```suggestion
      endpoint: 'io-azure-devops-github-ro'
```

2021-03-25 08:37 UTC, pasqualedevita commented on .devops/yarn-lock-upgrade.yml
>        endpoint: 'pagopa'
```suggestion
      endpoint: 'io-azure-devops-github-ro'
```

2021-03-25 08:39 UTC, pasqualedevita commented
change also here `api/v1/info`
https://github.com/pagopa/io-functions-template/blob/update-pipelines/Info/index.ts#L13

I don't known if we need to add also
`"route": "v1/info",`
https://github.com/pagopa/io-functions-pushnotifications/blob/master/Info/function.json#L8

2021-03-25 08:40 UTC, pasqualedevita commented
fix also danger issue

2021-03-25 08:46 UTC, gquadrati commented
> change also here `api/v1/info`
> https://github.com/pagopa/io-functions-template/blob/update-pipelines/Info/index.ts#L13
> 
> I don't known if we need to add also
> `"route": "v1/info",` like
> https://github.com/pagopa/io-functions-pushnotifications/blob/master/Info/function.json#L8

Done in [8d8f5ca](https://github.com/pagopa/io-functions-template/pull/21/commits/8d8f5ca6f59941a11eebea0445956990a5d87524)

2021-03-25 09:21 UTC, pasqualedevita reviewed
@balanza fix danger issue is out of scope?

2021-03-25 10:45 UTC, gquadrati commented
> @balanza fix danger issue is out of scope?

@pasqualedevita @balanza fixed in #23

2021-03-25 10:46 UTC, gquadrati approved these changes
LGTM

2021-03-25 11:00 UTC, pasqualedevita approved these changes
LGTM

2021-03-26 08:10 UTC, BurnedMarshal requested changes
If the express route is `api/v1/info` and the functions.json route is `v1/info`, we need to add `routePrefix=api` inside host.json file. Otherwise the route inside functions.json must be `api/v1/info` accordingly with the express route.

2021-03-26 08:37 UTC, gquadrati commented
> If the express route is `api/v1/info` and the functions.json route is `v1/info`, we need to add `routePrefix=api` inside host.json file. Otherwise the route inside functions.json must be `api/v1/info` accordingly with the express route.

Done in [83ab661](https://github.com/pagopa/io-functions-template/pull/21/commits/83ab6612934972d449b5c1a72387435de6a1a3c6)

2021-03-26 08:40 UTC, BurnedMarshal commented on Info/function.json
> +      "route": "/api/v1/info",
Be careful that the initial `/` doesn't work on production.
```suggestion
      "route": "api/v1/info",
```

2021-03-26 08:42 UTC, BurnedMarshal approved these changes
LGTM

2021-03-26 08:44 UTC, merged